# Generated by Django 3.2.20 on 2023-07-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('data_nascimento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('bigInt', models.BigIntegerField()),
                ('intervalo', models.DurationField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flutuante', models.FloatField()),
                ('inteiro', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
            ],
        ),
    ]
