# Generated by Django 4.2.3 on 2023-07-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20230707_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='estado',
        ),
    ]
